table statewise_results
	lineageTag: f8c40e46-38f9-459f-ba38-5de1366f0a11

	column Constituency
		dataType: string
		lineageTag: a2f413a4-753f-4d93-bc51-9c9dd2f13618
		summarizeBy: none
		sourceColumn: Constituency

		annotation SummarizationSetBy = Automatic

	column 'Const. No.'
		dataType: int64
		formatString: 0
		lineageTag: f843809c-544c-4595-996c-93ff344e7e49
		summarizeBy: sum
		sourceColumn: Const. No.

		annotation SummarizationSetBy = Automatic

	column 'Parliament Constituency'
		dataType: string
		lineageTag: 9c0a5c77-e098-44a8-8b36-7e71d37bf58c
		summarizeBy: none
		sourceColumn: Parliament Constituency

		annotation SummarizationSetBy = Automatic

	column 'Leading Candidate'
		dataType: string
		lineageTag: 38986384-f6e8-4b29-aded-6608c667546d
		summarizeBy: none
		sourceColumn: Leading Candidate

		annotation SummarizationSetBy = Automatic

	column 'Trailing Candidate'
		dataType: string
		lineageTag: 38b63090-1601-4e5e-835c-bcad35fd4eda
		summarizeBy: none
		sourceColumn: Trailing Candidate

		annotation SummarizationSetBy = Automatic

	column Margin
		dataType: int64
		formatString: 0
		lineageTag: ffc5d05c-7a30-45fe-bc8d-4af2b09cd217
		summarizeBy: sum
		sourceColumn: Margin

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 95fa6d50-7e99-443c-8d60-8e85b2d42478
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'State ID'
		dataType: string
		lineageTag: 18b2749c-627b-419d-974f-619d72c4db2c
		summarizeBy: none
		sourceColumn: State ID

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 7fcfbfcb-0679-47d0-8d60-4ef90e31d8b6
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition statewise_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manoj.c\Desktop\PowerBI\India-Elections-2024-SQL-PowerBI-Analysis\Power-BI\Power-BI-Data\statewise_results.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"Constituency", type text}, {"Const. No.", Int64.Type}, {"Parliament Constituency", type text}, {"Leading Candidate", type text}, {"Trailing Candidate", type text}, {"Margin", Int64.Type}, {"Status", type text}, {"State ID", type text}, {"Country", type text}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

